<?php
$title='Provider Details';
require __DIR__.'/../includes/header.php';
require __DIR__.'/../config/database.php';
require_valid_customer($pdo);
$requestId=(int)($_GET['request']??0);$providerId=(int)($_GET['provider']??0);
$st=$pdo->prepare("SELECT r.*,sc.name category,sp.name subproblem,pr.name province,d.name district,ci.name city,v.brand,v.model,v.vehicle_type,v.registration_number,v.transmission,v.fuel_type,v.manufacture_year,v.color,v.engine_capacity FROM assistance_requests r JOIN service_categories sc ON sc.id=r.category_id LEFT JOIN service_subproblems sp ON sp.id=r.subproblem_id LEFT JOIN provinces pr ON pr.id=r.province_id LEFT JOIN districts d ON d.id=r.district_id LEFT JOIN cities ci ON ci.id=r.city_id LEFT JOIN vehicles v ON v.id=r.vehicle_id WHERE r.id=? AND r.customer_id=? AND EXISTS(SELECT 1 FROM payments pay WHERE pay.request_id=r.id AND pay.payment_status='success') LIMIT 1");$st->execute([$requestId,$_SESSION['user_id']]);$r=$st->fetch();if(!$r)redirect(BASE_URL.'customer/dashboard.php');
$st=$pdo->prepare("SELECT p.*,u.phone,ci.name city,d.name district,pr.name province,COALESCE(pa.available,0) available FROM providers p JOIN users u ON u.id=p.user_id LEFT JOIN cities ci ON ci.id=p.city_id LEFT JOIN districts d ON d.id=p.district_id LEFT JOIN provinces pr ON pr.id=d.province_id LEFT JOIN provider_availability pa ON pa.provider_id=p.id WHERE p.id=? AND p.approval_status='approved' AND u.status='active' LIMIT 1");$st->execute([$providerId]);$p=$st->fetch();if(!$p)redirect(BASE_URL.'customer/providers.php?request='.$requestId);
$st=$pdo->prepare("SELECT sc.name category,sp.name subproblem FROM provider_services ps JOIN service_categories sc ON sc.id=ps.category_id LEFT JOIN service_subproblems sp ON sp.id=ps.subproblem_id WHERE ps.provider_id=? AND sc.status='active' ORDER BY sc.name,sp.name");$st->execute([$providerId]);$services=$st->fetchAll();
$st=$pdo->prepare("SELECT vt.name FROM provider_vehicle_types pvt JOIN vehicle_types vt ON vt.id=pvt.vehicle_type_id WHERE pvt.provider_id=? AND vt.status='active' ORDER BY vt.id");$st->execute([$providerId]);$supportedVehicles=$st->fetchAll(PDO::FETCH_COLUMN);
?>
<section class="section-pad"><div class="container"><div class="mb-4"><a href="providers.php?request=<?=$requestId?>" class="btn btn-outline-secondary btn-sm mb-3"><i class="bi bi-arrow-left me-1"></i> Back to providers</a><span class="text-warning fw-bold d-block">SERVICE PROVIDER</span><h1 class="fw-bold mt-2 mb-1"><?=e($p['business_name'])?></h1><p class="text-muted mb-0"><?=e($p['city']?:'Service location')?><?=!empty($p['district'])?' · '.e($p['district']).' District':''?></p></div>
<div class="row g-4"><div class="col-lg-5"><div class="card border-0 shadow-sm rounded-4 p-4 h-100"><div class="d-flex justify-content-between align-items-start"><div><h4 class="fw-bold mb-1"><?=e($p['business_name'])?></h4><div class="small text-muted">Owner: <?=e($p['owner_name']?:'Not provided')?></div></div><span class="badge <?=$p['available']?'text-bg-success':'text-bg-secondary'?>"><?=$p['available']?'Available':'Unavailable'?></span></div><hr><p><i class="bi bi-telephone me-2"></i><?=e($p['phone']?:'Phone not provided')?></p><p><i class="bi bi-whatsapp me-2"></i><?=e($p['whatsapp']?:'WhatsApp not provided')?></p><p><i class="bi bi-geo-alt me-2"></i><?=e($p['address']?:'Service address not provided')?></p><?php if(!empty($p['google_maps_link'])):?><p><i class="bi bi-map me-2"></i><a href="<?=e($p['google_maps_link'])?>" target="_blank" rel="noopener">Open Google Maps location</a></p><?php endif;?><p><i class="bi bi-clock me-2"></i><?=($p['emergency_24h']?'24-hour emergency service':(($p['opening_time']&&$p['closing_time'])?e(substr($p['opening_time'],0,5).' - '.substr($p['closing_time'],0,5)):'Hours not provided'))?></p><p class="text-muted small"><?=e($p['description']?:'No additional description provided.')?></p><?php if(!empty($p['phone'])):?><a class="btn btn-dark w-100" href="tel:<?=e($p['phone'])?>"><i class="bi bi-telephone me-1"></i> Call provider</a><?php endif;?></div></div>
<div class="col-lg-7"><div class="card border-0 shadow-sm rounded-4 p-4 mb-4"><h4 class="fw-bold">Vehicle types serviced</h4><div class="d-flex flex-wrap gap-2 mt-2"><?php foreach($supportedVehicles as $vt):?><span class="badge text-bg-light border text-dark"><?=e($vt)?></span><?php endforeach;?></div></div><div class="card border-0 shadow-sm rounded-4 p-4 mb-4"><h4 class="fw-bold">Services offered</h4><div class="row g-2 mt-1"><?php foreach($services as $s):?><div class="col-md-6"><div class="border rounded-3 p-3"><strong><?=e($s['category'])?></strong><?php if($s['subproblem']):?><div class="small text-muted mt-1"><i class="bi bi-check2-circle me-1"></i><?=e($s['subproblem'])?></div><?php endif;?></div></div><?php endforeach;?></div></div>
<div class="card border-0 shadow-sm rounded-4 p-4" id="service-location"><div class="d-flex justify-content-between align-items-center gap-2 mb-3"><div><h4 class="fw-bold mb-1">Provider service location</h4><p class="text-muted small mb-0"><?=e($p['address']?:'Service address not provided')?><?=!empty($p['city'])?' · '.e($p['city']):''?></p></div><button class="btn btn-outline-primary" id="myLocationBtn" type="button"><i class="bi bi-crosshair me-1"></i> Use my GPS</button><button class="btn btn-primary" id="directionsBtn" type="button" <?=($p['latitude']===null||$p['longitude']===null||$r['latitude']===null||$r['longitude']===null)?'disabled':''?>><i class="bi bi-sign-turn-right me-1"></i> Directions</button></div><div id="providerMap" class="provider-map"></div><div id="routeStatus" class="small text-muted mt-2">Click Directions to draw the route from the breakdown location to this provider.</div></div></div></div>
</div></section>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
<script>
const breakdown={lat:<?=json_encode($r['latitude'])?>,lng:<?=json_encode($r['longitude'])?>},provider={lat:<?=json_encode($p['latitude'])?>,lng:<?=json_encode($p['longitude'])?>};let map=L.map('providerMap').setView([provider.lat||breakdown.lat||7.8731,provider.lng||breakdown.lng||80.7718],13),providerMarker=null,startMarker=null,routeLayer=null;
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
if(provider.lat!==null&&provider.lng!==null){providerMarker=L.marker([Number(provider.lat),Number(provider.lng)]).addTo(map).bindPopup('<strong><?=e($p['business_name'])?></strong><br><?=e($p['address']?:'Service location')?>').openPopup();}
if(breakdown.lat!==null&&breakdown.lng!==null){startMarker=L.circleMarker([Number(breakdown.lat),Number(breakdown.lng)],{radius:8}).addTo(map).bindPopup('<strong>Your breakdown location</strong>');}
function fitPoints(){const pts=[];if(provider.lat!==null&&provider.lng!==null)pts.push([Number(provider.lat),Number(provider.lng)]);if(breakdown.lat!==null&&breakdown.lng!==null)pts.push([Number(breakdown.lat),Number(breakdown.lng)]);if(pts.length>1)map.fitBounds(pts,{padding:[35,35]});}
fitPoints();
async function drawRoute(startLat,startLng){if(provider.lat===null||provider.lng===null){document.getElementById('routeStatus').textContent='This provider has not registered a precise map location yet.';return;}const status=document.getElementById('routeStatus');status.textContent='Calculating route...';try{const url=`https://router.project-osrm.org/route/v1/driving/${startLng},${startLat};${provider.lng},${provider.lat}?overview=full&geometries=geojson`;const res=await fetch(url);if(!res.ok)throw Error();const data=await res.json();if(data.code!=='Ok'||!data.routes?.length)throw Error();if(routeLayer)map.removeLayer(routeLayer);routeLayer=L.geoJSON(data.routes[0].geometry,{style:{color:'#0d6efd',weight:6,opacity:.9}}).addTo(map);map.fitBounds(routeLayer.getBounds(),{padding:[45,45]});const km=(data.routes[0].distance/1000).toFixed(1),mins=Math.round(data.routes[0].duration/60);status.innerHTML=`<strong>Route:</strong> ${km} km · about ${mins} min driving. <span class="text-muted">Blue line = route.</span>`;}catch(e){status.textContent='Route could not be calculated right now. Please try again.';}}
document.getElementById('directionsBtn').addEventListener('click',()=>{if(breakdown.lat!==null&&breakdown.lng!==null)drawRoute(Number(breakdown.lat),Number(breakdown.lng));});document.getElementById('myLocationBtn').addEventListener('click',()=>{if(!navigator.geolocation){document.getElementById('routeStatus').textContent='Your browser does not support GPS location.';return;}document.getElementById('routeStatus').textContent='Getting your current GPS location...';navigator.geolocation.getCurrentPosition(pos=>drawRoute(pos.coords.latitude,pos.coords.longitude),()=>document.getElementById('routeStatus').textContent='Location permission was denied or unavailable.',{enableHighAccuracy:true,timeout:20000,maximumAge:0});});
</script>
<?php require __DIR__.'/../includes/footer.php'; ?>
