<?php
$title='Add Provider';
require __DIR__.'/../includes/header.php';
require_login('admin');
require __DIR__.'/../config/database.php';
require_once __DIR__.'/../includes/functions.php';
require_once __DIR__.'/../includes/location_bootstrap.php';
ensure_sri_lanka_locations($pdo);
$cats=$pdo->query("SELECT id,name FROM service_categories WHERE status='active' ORDER BY id")->fetchAll();
$vehicleTypes=$pdo->query("SELECT id,name FROM vehicle_types WHERE status='active' ORDER BY id")->fetchAll();
$provinces=$pdo->query('SELECT id,name FROM provinces ORDER BY id')->fetchAll();
$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  try{
    $name=trim($_POST['owner_name']??''); $email=trim($_POST['email']??''); $phone=trim($_POST['phone']??''); $password=$_POST['password']??'';
    $business=trim($_POST['business_name']??''); $whatsapp=trim($_POST['whatsapp']??''); $address=trim($_POST['address']??''); $maps=trim($_POST['google_maps_link']??'');
    $province=(int)($_POST['province_id']??0); $district=(int)($_POST['district_id']??0); $city=(int)($_POST['city_id']??0);
    $lat=($_POST['latitude']??'')!==''?(float)$_POST['latitude']:null; $lng=($_POST['longitude']??'')!==''?(float)$_POST['longitude']:null; $acc=($_POST['location_accuracy']??'')!==''?(float)$_POST['location_accuracy']:null;
    $categoryIds=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['category_ids']??[])))));
    $vehicleIds=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['vehicle_type_ids']??[])))));
    if($maps!==''){[$mlat,$mlng]=extract_google_maps_coordinates($maps);if($mlat!==null&&$mlng!==null){$lat=$mlat;$lng=$mlng;$acc=null;}}
    if(!$business||!$name||!$email||!$password) throw new RuntimeException('Business name, contact person, email and password are required.');
    if(strlen($password)<6) throw new RuntimeException('Provider password must contain at least 6 characters.');
    if(!$categoryIds) throw new RuntimeException('Select at least one service category.');
    if(!$vehicleIds) throw new RuntimeException('Select at least one vehicle type.');
    if(!$province||!$district||!$city) throw new RuntimeException('Select the service province, district and town/area.');
    if($lat===null||$lng===null) throw new RuntimeException('Set the service-station location using the map, current location, or a Google Maps link.');
    $q=$pdo->prepare('SELECT id FROM districts WHERE id=? AND province_id=?');$q->execute([$district,$province]);if(!$q->fetchColumn())throw new RuntimeException('Invalid district for selected province.');
    ensure_sri_lanka_cities($pdo,$district); $q=$pdo->prepare('SELECT id FROM cities WHERE id=? AND district_id=?');$q->execute([$city,$district]);if(!$q->fetchColumn())throw new RuntimeException('Invalid town/area for selected district.');
    $pdo->beginTransaction();
    $st=$pdo->prepare("INSERT INTO users(name,email,phone,password_hash,role,status) VALUES(?,?,?,?, 'provider','active')");$st->execute([$name,$email,$phone,password_hash($password,PASSWORD_DEFAULT)]);$uid=(int)$pdo->lastInsertId();
    $st=$pdo->prepare("INSERT INTO providers(user_id,business_name,owner_name,whatsapp,address,google_maps_link,latitude,longitude,location_accuracy,district_id,city_id,description,emergency_24h,approval_status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,'approved')");
    $st->execute([$uid,$business,$name,$whatsapp,$address,$maps!==''?$maps:null,$lat,$lng,$acc,$district,$city,trim($_POST['description']??''),isset($_POST['emergency'])?1:0]);$pid=(int)$pdo->lastInsertId();
    $st=$pdo->prepare('INSERT INTO provider_services(provider_id,category_id) VALUES(?,?)');foreach($categoryIds as $id)$st->execute([$pid,$id]);
    $st=$pdo->prepare('INSERT INTO provider_vehicle_types(provider_id,vehicle_type_id) VALUES(?,?)');foreach($vehicleIds as $id)$st->execute([$pid,$id]);
    $pdo->prepare('INSERT INTO provider_availability(provider_id,available) VALUES(?,1)')->execute([$pid]);
    $pdo->commit(); redirect(BASE_URL.'admin/providers.php?created=1');
  }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'Unable to create provider. The email may already be in use.';}
}
$oldCats=array_map('intval',(array)($_POST['category_ids']??[]));$oldVehicles=array_map('intval',(array)($_POST['vehicle_type_ids']??[]));
?>
<section class="section-pad"><div class="container"><div class="col-lg-10 mx-auto card border-0 shadow-sm p-4 rounded-4"><div class="d-flex justify-content-between align-items-center mb-2"><div><h2 class="fw-bold mb-1">Add Service Provider</h2><p class="text-muted mb-0">Create and approve provider accounts from the administrator portal.</p></div><a href="providers.php" class="btn btn-outline-secondary">Back</a></div>
<?php if($error):?><div class="alert alert-danger mt-3"><?=e($error)?></div><?php endif;?>
<form method="post" class="row g-3 mt-1">
<div class="col-md-6"><label class="form-label">Business name *</label><input class="form-control" name="business_name" value="<?=e($_POST['business_name']??'')?>" required></div>
<div class="col-md-6"><label class="form-label">Owner / contact person *</label><input class="form-control" name="owner_name" value="<?=e($_POST['owner_name']??'')?>" required></div>
<div class="col-md-6"><label class="form-label">Provider email *</label><input class="form-control" type="email" name="email" value="<?=e($_POST['email']??'')?>" required></div>
<div class="col-md-6"><label class="form-label">Phone *</label><input class="form-control" name="phone" value="<?=e($_POST['phone']??'')?>" required></div>
<div class="col-md-6"><label class="form-label">WhatsApp</label><input class="form-control" name="whatsapp" value="<?=e($_POST['whatsapp']??'')?>"></div>
<div class="col-md-6"><label class="form-label">Provider login password *</label><input class="form-control" type="password" name="password" minlength="6" required></div>
<div class="col-12"><div class="border rounded-4 p-3 bg-light-subtle"><label class="form-label fw-semibold">Vehicle types serviced *</label><div class="row g-2"><?php foreach($vehicleTypes as $t):?><div class="col-sm-6 col-lg-4"><label class="form-check border rounded-3 p-2 ps-5 bg-white h-100"><input class="form-check-input" type="checkbox" name="vehicle_type_ids[]" value="<?=$t['id']?>" <?=in_array((int)$t['id'],$oldVehicles,true)?'checked':''?>> <span class="form-check-label"><?=e($t['name'])?></span></label></div><?php endforeach;?></div></div></div>
<div class="col-12"><div class="border rounded-4 p-3 bg-light-subtle"><label class="form-label fw-semibold">Service categories *</label><div class="row g-2"><?php foreach($cats as $c):?><div class="col-sm-6 col-lg-3"><label class="form-check border rounded-3 p-2 ps-5 bg-white h-100"><input class="form-check-input" type="checkbox" name="category_ids[]" value="<?=$c['id']?>" <?=in_array((int)$c['id'],$oldCats,true)?'checked':''?>> <span class="form-check-label"><?=e($c['name'])?></span></label></div><?php endforeach;?></div></div></div>
<div class="col-md-4"><label class="form-label">Province *</label><select class="form-select" id="adminProviderProvince" name="province_id" required><option value="">Select province</option><?php foreach($provinces as $p):?><option value="<?=$p['id']?>" <?=((int)($_POST['province_id']??0)===(int)$p['id'])?'selected':''?>><?=e($p['name'])?> Province</option><?php endforeach;?></select></div>
<div class="col-md-4"><label class="form-label">District *</label><select class="form-select" id="adminProviderDistrict" name="district_id" required><option value="">Select province first</option></select></div>
<div class="col-md-4"><label class="form-label">Town / Area *</label><select class="form-select" id="adminProviderCity" name="city_id" required><option value="">Select district first</option></select></div>
<div class="col-12"><label class="form-label">Service station address *</label><input class="form-control" name="address" value="<?=e($_POST['address']??'')?>" required></div>
<div class="col-12"><label class="form-label">Google Maps location link <span class="text-muted">(optional)</span></label><input class="form-control" id="adminProviderGoogle" name="google_maps_link" value="<?=e($_POST['google_maps_link']??'')?>" placeholder="Paste the Google Maps link for the service station"><div class="form-text">If the link exposes coordinates, INFINEX will read them and place the station on the Leaflet map.</div></div>
<div class="col-12"><div class="location-picker"><label class="location-label">Exact service station location *</label><div class="location-search-wrapper"><i class="bi bi-geo-alt location-search-icon"></i><input class="location-search" id="adminProviderSearch" placeholder="Search service station location..."></div><div class="location-actions"><button type="button" class="current-location-btn" id="adminProviderCurrent"><i class="bi bi-crosshair"></i> Use current location</button><button type="button" class="btn btn-outline-primary btn-sm ms-2" id="adminProviderUseGoogle"><i class="bi bi-link-45deg"></i> Use Google Maps link</button><span id="adminProviderStatus" class="location-status"></span></div><div id="adminProviderMap" class="location-map"></div></div><input type="hidden" name="latitude" id="adminProviderLat"><input type="hidden" name="longitude" id="adminProviderLng"><input type="hidden" name="location_accuracy" id="adminProviderAcc"></div>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="3"><?=e($_POST['description']??'')?></textarea></div><div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="emergency" <?=isset($_POST['emergency'])?'checked':''?>> <label class="form-check-label">24-hour emergency service</label></div>
<div class="col-12"><button class="btn btn-dark px-4">Create & Approve Provider</button></div>
</form></div></div></section>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const ap=document.getElementById('adminProviderProvince'),ad=document.getElementById('adminProviderDistrict'),ac=document.getElementById('adminProviderCity');let savedD=<?=json_encode((int)($_POST['district_id']??0))?>,savedC=<?=json_encode((int)($_POST['city_id']??0))?>;
async function loadAD(){ad.disabled=true;ad.innerHTML='<option>Loading districts...</option>';ac.disabled=true;ac.innerHTML='<option>Select district first</option>';if(!ap.value){ad.innerHTML='<option>Select province first</option>';return;}try{const r=await fetch('../customer/get-districts.php?province_id='+encodeURIComponent(ap.value));const a=await r.json();ad.innerHTML='<option value="">Select district</option>';a.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name+' District';if(Number(x.id)===savedD)o.selected=true;ad.appendChild(o)});ad.disabled=!a.length;if(ad.value)loadAC(ad.value);}catch(e){ad.innerHTML='<option>Unable to load districts</option>';}}
async function loadAC(id){ac.disabled=true;ac.innerHTML='<option>Loading towns...</option>';if(!id){ac.innerHTML='<option>Select district first</option>';return;}try{const r=await fetch('../customer/get-cities.php?district_id='+encodeURIComponent(id));const a=await r.json();ac.innerHTML='<option value="">Select town / area</option>';a.forEach(x=>{const o=document.createElement('option');o.value=x.id;o.textContent=x.name+(x.postcode?' ('+x.postcode+')':'');if(Number(x.id)===savedC)o.selected=true;ac.appendChild(o)});ac.disabled=!a.length;}catch(e){ac.innerHTML='<option>Unable to load towns</option>';}}
ap.onchange=()=>{savedD=0;savedC=0;loadAD()};ad.onchange=()=>{savedC=0;loadAC(ad.value)};loadAD();
const amap=L.map('adminProviderMap').setView([7.8731,80.7718],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(amap);let amarker=null;const ast=document.getElementById('adminProviderStatus'),asearch=document.getElementById('adminProviderSearch'),ag=document.getElementById('adminProviderGoogle');
function setALoc(lat,lng,address='',acc=''){document.getElementById('adminProviderLat').value=Number(lat).toFixed(8);document.getElementById('adminProviderLng').value=Number(lng).toFixed(8);document.getElementById('adminProviderAcc').value=acc!==''?Number(acc).toFixed(2):'';if(address)asearch.value=address;amap.setView([lat,lng],17);if(!amarker){amarker=L.marker([lat,lng],{draggable:true}).addTo(amap);amarker.on('dragend',async()=>{const x=amarker.getLatLng();try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${x.lat}&lon=${x.lng}`);const d=await r.json();setALoc(x.lat,x.lng,d.display_name||'','');}catch(e){setALoc(x.lat,x.lng,'','');}})}else amarker.setLatLng([lat,lng]);ast.textContent='Service station location selected.';}
function parseG(url){url=url.trim();let m=url.match(/@(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/);if(!m)m=url.match(/!3d(-?\d+(?:\.\d+)?)!4d(-?\d+(?:\.\d+)?)/);if(!m)m=url.match(/[?&](?:q|query|ll|center)=(-?\d+(?:\.\d+)?)[,%2C]+(-?\d+(?:\.\d+)?)/i);if(!m){try{m=decodeURIComponent(url).match(/(-?\d{1,3}\.\d+)[,\s]+(-?\d{1,3}\.\d+)/);}catch(e){}}if(!m)return null;const lat=Number(m[1]),lng=Number(m[2]);return Math.abs(lat)<=90&&Math.abs(lng)<=180?[lat,lng]:null;}
function useG(){const c=parseG(ag.value);if(c){setALoc(c[0],c[1],ag.value,'');ast.textContent='Google Maps coordinates loaded into Leaflet.';}else if(ag.value.trim())ast.textContent='This Google Maps link does not expose coordinates. Select the station on the map or use current location.';}
document.getElementById('adminProviderUseGoogle').onclick=useG;ag.addEventListener('change',useG);ag.addEventListener('paste',()=>setTimeout(useG,50));document.getElementById('adminProviderCurrent').onclick=()=>navigator.geolocation.getCurrentPosition(async x=>{const {latitude,longitude,accuracy}=x.coords;try{const r=await fetch(`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${latitude}&lon=${longitude}`);const d=await r.json();setALoc(latitude,longitude,d.display_name||'',accuracy);}catch(e){setALoc(latitude,longitude,'',accuracy)}},()=>ast.textContent='Location permission was denied or unavailable.',{enableHighAccuracy:true,timeout:20000,maximumAge:0});asearch.addEventListener('input',()=>{const q=asearch.value.trim();if(q.length<3)return;fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=5&countrycodes=lk&q='+encodeURIComponent(q)).then(r=>r.json()).then(a=>{if(a[0])setALoc(a[0].lat,a[0].lon,a[0].display_name,'');}).catch(()=>{});});amap.on('click',e=>setALoc(e.latlng.lat,e.latlng.lng,'',''));
</script><?php require __DIR__.'/../includes/footer.php'; ?>
