<?php
$title='Available Providers';
require __DIR__.'/../includes/header.php';
require __DIR__.'/../config/database.php';
require_valid_customer($pdo);
$id=(int)($_GET['request']??0);
$st=$pdo->prepare("SELECT r.*,sc.name category,sp.name subproblem,d.name district,pr.name province,ci.name city,pay.id payment_id,v.brand,v.model,v.vehicle_type,v.registration_number,v.transmission,v.fuel_type,v.manufacture_year,v.color,v.engine_capacity FROM assistance_requests r JOIN service_categories sc ON sc.id=r.category_id LEFT JOIN service_subproblems sp ON sp.id=r.subproblem_id LEFT JOIN provinces pr ON pr.id=r.province_id LEFT JOIN districts d ON d.id=r.district_id LEFT JOIN cities ci ON ci.id=r.city_id LEFT JOIN vehicles v ON v.id=r.vehicle_id JOIN payments pay ON pay.request_id=r.id AND pay.payment_status='success' WHERE r.id=? AND r.customer_id=? ORDER BY pay.id DESC LIMIT 1");
$st->execute([$id,$_SESSION['user_id']]);$r=$st->fetch();if(!$r)redirect(BASE_URL.'customer/dashboard.php');
$st=$pdo->prepare("SELECT DISTINCT p.id,p.business_name,p.owner_name,p.whatsapp,p.address,p.description,p.rating,p.latitude,p.longitude,p.opening_time,p.closing_time,p.emergency_24h,u.phone,ci.name city,d.name district,COALESCE(pa.available,0) available, CASE WHEN p.latitude IS NOT NULL AND p.longitude IS NOT NULL AND r.latitude IS NOT NULL AND r.longitude IS NOT NULL THEN 6371*2*ASIN(SQRT(POWER(SIN(RADIANS(p.latitude-r.latitude)/2),2)+COS(RADIANS(r.latitude))*COS(RADIANS(p.latitude))*POWER(SIN(RADIANS(p.longitude-r.longitude)/2),2))) ELSE NULL END AS distance_km FROM providers p JOIN users u ON u.id=p.user_id JOIN provider_services ps ON ps.provider_id=p.id AND ps.category_id=? JOIN provider_vehicle_types pvt ON pvt.provider_id=p.id JOIN vehicle_types vt ON vt.id=pvt.vehicle_type_id LEFT JOIN cities ci ON ci.id=p.city_id LEFT JOIN districts d ON d.id=p.district_id LEFT JOIN provider_availability pa ON pa.provider_id=p.id JOIN assistance_requests r ON r.id=? WHERE p.approval_status='approved' AND u.status='active' AND (vt.name=? OR vt.name='All Vehicle Types') ORDER BY distance_km IS NULL ASC,distance_km ASC,COALESCE(pa.available,0) DESC,p.rating DESC,p.business_name ASC");
$st->execute([$r['category_id'],$id,$r['vehicle_type']]);$providers=$st->fetchAll();
?>
<section class="section-pad"><div class="container">
<div class="d-flex justify-content-between align-items-center mb-4"><div><span class="text-warning fw-bold">PAYMENT SUCCESSFUL</span><h1 class="fw-bold">Nearby service providers</h1><p class="text-muted mb-0">Providers are sorted from nearest to farthest from your selected breakdown location.</p></div><span class="badge text-bg-success">Details unlocked</span></div>
<div class="row g-3 mb-4"><div class="col-lg-7"><div class="card border-0 shadow-sm rounded-4 p-3 h-100"><div class="d-flex gap-3"><i class="bi bi-geo-alt-fill fs-3 text-primary"></i><div><strong><?=e($r['address'])?></strong><div class="small text-muted"><?=e($r['province'])?> Province · <?=e($r['district'])?> District · <?=e($r['city'])?></div></div></div></div></div><div class="col-lg-5"><div class="vehicle-summary-strip h-100"><i class="bi bi-car-front-fill"></i><div><strong><?=e($r['brand'].' '.$r['model'])?></strong><small><?=e($r['registration_number'])?> · <?=e($r['vehicle_type'])?> · <?=e($r['transmission'])?></small></div></div></div></div>
<?php if(!$providers):?><div class="alert alert-warning">No approved provider has been registered yet. Please try again later.</div><?php endif;?>
<div class="row g-4">
<?php foreach($providers as $p):?><div class="col-md-6 col-xl-4"><div class="card border-0 shadow-sm rounded-4 p-4 h-100 provider-result-card"><div class="d-flex justify-content-between gap-2"><div><h5 class="fw-bold mb-1"><?=e($p['business_name'])?></h5><span class="small text-muted"><?=e($p['city']?:'Service location not specified')?><?=!empty($p['district'])?' · '.e($p['district']):''?></span></div><span class="badge <?=$p['available']?'text-bg-success':'text-bg-secondary'?>"><?=$p['available']?'Available':'Unavailable'?></span></div><div class="my-3"><span class="badge text-bg-light border text-dark"><i class="bi bi-signpost-2 me-1"></i><?=is_null($p['distance_km'])?'Distance unavailable':number_format((float)$p['distance_km'],1).' km away'?></span><?php if($p['rating']>0):?><span class="badge text-bg-light border text-dark ms-1"><i class="bi bi-star-fill me-1"></i><?=number_format((float)$p['rating'],1)?></span><?php endif;?></div><div class="small text-muted mb-2"><i class="bi bi-car-front me-1"></i>Vehicle compatibility verified for <?=e($r['vehicle_type'])?></div><a class="small mb-2 text-decoration-none d-block" href="provider-details.php?request=<?=$id?>&provider=<?=$p['id']?>#service-location"><i class="bi bi-geo-alt me-1"></i><?=e($p['address']?:'Service address not provided')?> · <span class="text-primary">View on map</span></a><p class="small text-muted flex-grow-1"><?=e($p['description']?:'Roadside assistance provider')?></p><div class="d-flex gap-2 mt-auto"><a class="btn btn-dark flex-fill" href="provider-details.php?request=<?=$id?>&provider=<?=$p['id']?>"><i class="bi bi-building me-1"></i> View provider</a><?php if(!empty($p['phone'])):?><a class="btn btn-outline-dark" href="tel:<?=e($p['phone'])?>"><i class="bi bi-telephone"></i></a><?php endif;?></div></div></div><?php endforeach;?>
</div><div class="alert alert-light border mt-4 small"><strong>How distance works:</strong> The list uses the latitude/longitude of your breakdown location and the provider's registered service location. Providers without a precise service coordinate appear after providers with calculated distances.</div>
</div></section>
<?php require __DIR__.'/../includes/footer.php'; ?>
