<?php
$title='Edit Provider';
require __DIR__.'/../includes/header.php';
require_login('admin');
require __DIR__.'/../config/database.php';
require_once __DIR__.'/../includes/functions.php';
require_once __DIR__.'/../includes/location_bootstrap.php';
ensure_sri_lanka_locations($pdo);
$id=(int)($_GET['id']??0);
$st=$pdo->prepare("SELECT p.*,u.name,u.email,u.phone,d.province_id FROM providers p JOIN users u ON u.id=p.user_id LEFT JOIN districts d ON d.id=p.district_id WHERE p.id=? LIMIT 1");$st->execute([$id]);$p=$st->fetch();if(!$p)exit('Provider not found.');
$cats=$pdo->query("SELECT id,name FROM service_categories WHERE status='active' ORDER BY id")->fetchAll();$types=$pdo->query("SELECT id,name FROM vehicle_types WHERE status='active' ORDER BY id")->fetchAll();$provinces=$pdo->query('SELECT id,name FROM provinces ORDER BY id')->fetchAll();
$q=$pdo->prepare('SELECT category_id FROM provider_services WHERE provider_id=?');$q->execute([$id]);$selCats=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));$q=$pdo->prepare('SELECT vehicle_type_id FROM provider_vehicle_types WHERE provider_id=?');$q->execute([$id]);$selTypes=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));
$msg='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 try{
  $province=(int)($_POST['province_id']??0);$district=(int)($_POST['district_id']??0);$city=(int)($_POST['city_id']??0);$maps=trim($_POST['google_maps_link']??'');$lat=($_POST['latitude']??'')!==''?(float)$_POST['latitude']:null;$lng=($_POST['longitude']??'')!==''?(float)$_POST['longitude']:null;$acc=($_POST['location_accuracy']??'')!==''?(float)$_POST['location_accuracy']:null;$cat=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['category_ids']??[])))));$typ=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['vehicle_type_ids']??[])))));
  if($maps!==''){[$mlat,$mlng]=extract_google_maps_coordinates($maps);if($mlat!==null&&$mlng!==null){$lat=$mlat;$lng=$mlng;$acc=null;}}
  if(!$province||!$district||!$city||$lat===null||$lng===null)throw new RuntimeException('Complete the service location and map coordinates.');if(!$cat||!$typ)throw new RuntimeException('Select at least one service category and vehicle type.');
  $q=$pdo->prepare('SELECT id FROM districts WHERE id=? AND province_id=?');$q->execute([$district,$province]);if(!$q->fetchColumn())throw new RuntimeException('Invalid district.');ensure_sri_lanka_cities($pdo,$district);$q=$pdo->prepare('SELECT id FROM cities WHERE id=? AND district_id=?');$q->execute([$city,$district]);if(!$q->fetchColumn())throw new RuntimeException('Invalid town/area.');
  $pdo->beginTransaction();$pdo->prepare('UPDATE users SET name=?,email=?,phone=? WHERE id=?')->execute([trim($_POST['owner_name']),trim($_POST['email']),trim($_POST['phone']),$p['user_id']]);$pdo->prepare('UPDATE providers SET business_name=?,owner_name=?,whatsapp=?,address=?,google_maps_link=?,latitude=?,longitude=?,location_accuracy=?,district_id=?,city_id=?,description=?,emergency_24h=?,approval_status=? WHERE id=?')->execute([trim($_POST['business_name']),trim($_POST['owner_name']),trim($_POST['whatsapp']),trim($_POST['address']),$maps!==''?$maps:null,$lat,$lng,$acc,$district,$city,trim($_POST['description']),isset($_POST['emergency'])?1:0,$_POST['approval_status']??'approved',$id]);
  $pdo->prepare('DELETE FROM provider_services WHERE provider_id=?')->execute([$id]);$ins=$pdo->prepare('INSERT INTO provider_services(provider_id,category_id) VALUES(?,?)');foreach($cat as $x)$ins->execute([$id,$x]);$pdo->prepare('DELETE FROM provider_vehicle_types WHERE provider_id=?')->execute([$id]);$ins=$pdo->prepare('INSERT INTO provider_vehicle_types(provider_id,vehicle_type_id) VALUES(?,?)');foreach($typ as $x)$ins->execute([$id,$x]);$newStatus=($_POST['approval_status']??'approved')==='approved'?'active':(($_POST['approval_status']??'approved')==='disabled'?'disabled':'pending');$pdo->prepare('UPDATE users SET status=? WHERE id=?')->execute([$newStatus,$p['user_id']]);$pdo->commit();$msg='Provider details updated.';$st->execute([$id]);$p=$st->fetch();$selCats=$cat;$selTypes=$typ;
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e->getMessage();}
}
?>
<section class="section-pad"><div class="container"><div class="col-lg-10 mx-auto card border-0 shadow-sm p-4 rounded-4"><div class="d-flex justify-content-between align-items-center"><div><h2 class="fw-bold mb-1">Edit Provider</h2><p class="text-muted mb-0">Administrator control over provider account, services and station location.</p></div><a class="btn btn-outline-secondary" href="providers.php">Back</a></div><?php if($msg):?><div class="alert alert-success mt-3"><?=e($msg)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger mt-3"><?=e($error)?></div><?php endif;?><form method="post" class="row g-3 mt-1">
<div class="col-md-6"><label class="form-label">Business name</label><input class="form-control" name="business_name" value="<?=e($p['business_name'])?>" required></div><div class="col-md-6"><label class="form-label">Owner/contact</label><input class="form-control" name="owner_name" value="<?=e($p['owner_name']??$p['name'])?>" required></div><div class="col-md-6"><label class="form-label">Email</label><input class="form-control" type="email" name="email" value="<?=e($p['email'])?>" required></div><div class="col-md-6"><label class="form-label">Phone</label><input class="form-control" name="phone" value="<?=e($p['phone'])?>"></div><div class="col-md-6"><label class="form-label">WhatsApp</label><input class="form-control" name="whatsapp" value="<?=e($p['whatsapp']??'')?>"></div><div class="col-md-6"><label class="form-label">Approval status</label><select class="form-select" name="approval_status"><option value="approved" <?=$p['approval_status']==='approved'?'selected':''?>>Approved</option><option value="pending" <?=$p['approval_status']==='pending'?'selected':''?>>Pending</option><option value="rejected" <?=$p['approval_status']==='rejected'?'selected':''?>>Rejected</option><option value="disabled" <?=$p['approval_status']==='disabled'?'selected':''?>>Disabled</option></select></div>
<div class="col-12"><div class="border rounded-4 p-3 bg-light-subtle"><label class="form-label fw-semibold">Vehicle types serviced *</label><div class="row g-2"><?php foreach($types as $t):?><div class="col-sm-6 col-lg-4"><label class="form-check border rounded-3 p-2 ps-5 bg-white"><input class="form-check-input" type="checkbox" name="vehicle_type_ids[]" value="<?=$t['id']?>" <?=in_array((int)$t['id'],$selTypes,true)?'checked':''?>> <?=e($t['name'])?></label></div><?php endforeach;?></div></div></div>
<div class="col-12"><div class="border rounded-4 p-3 bg-light-subtle"><label class="form-label fw-semibold">Service categories *</label><div class="row g-2"><?php foreach($cats as $c):?><div class="col-sm-6 col-lg-3"><label class="form-check border rounded-3 p-2 ps-5 bg-white"><input class="form-check-input" type="checkbox" name="category_ids[]" value="<?=$c['id']?>" <?=in_array((int)$c['id'],$selCats,true)?'checked':''?>> <?=e($c['name'])?></label></div><?php endforeach;?></div></div></div>
<div class="col-md-4"><label class="form-label">Province</label><select class="form-select" id="ep" name="province_id" required><?php foreach($provinces as $x):?><option value="<?=$x['id']?>" <?=$x['id']==(int)$p['province_id']?'selected':''?>><?=e($x['name'])?> Province</option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">District</label><select class="form-select" id="ed" name="district_id" required></select></div><div class="col-md-4"><label class="form-label">Town / Area</label><select class="form-select" id="ec" name="city_id" required></select></div>
<div class="col-12"><label class="form-label">Service address</label><input class="form-control" name="address" value="<?=e($p['address']??'')?>" required></div><div class="col-12"><label class="form-label">Google Maps location link</label><input class="form-control" id="eg" name="google_maps_link" value="<?=e($p['google_maps_link']??'')?>"></div>
<div class="col-12"><div class="location-picker"><label class="location-label">Exact service station location *</label><div class="location-search-wrapper"><i class="bi bi-geo-alt location-search-icon"></i><input class="location-search" id="es" placeholder="Search service location..."></div><div class="location-actions"><button type="button" class="current-location-btn" id="egps"><i class="bi bi-crosshair"></i> Use current location</button><button type="button" class="btn btn-outline-primary btn-sm ms-2" id="eguse"><i class="bi bi-link-45deg"></i> Use Google Maps link</button><span id="est" class="location-status"></span></div><div id="emap" class="location-map"></div></div><input type="hidden" name="latitude" id="elat" value="<?=e((string)$p['latitude'])?>"><input type="hidden" name="longitude" id="elng" value="<?=e((string)$p['longitude'])?>"><input type="hidden" name="location_accuracy" id="eacc" value="<?=e((string)$p['location_accuracy'])?>"></div>
<div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="3"><?=e($p['description']??'')?></textarea></div><div class="col-12 form-check ms-2"><input class="form-check-input" type="checkbox" name="emergency" <?=$p['emergency_24h']?'checked':''?>> <label class="form-check-label">24-hour emergency service</label></div><div class="col-12"><button class="btn btn-dark">Save Provider Changes</button></div></form></div></div></section>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>
const ep=document.getElementById('ep'),ed=document.getElementById('ed'),ec=document.getElementById('ec');let sd=<?=json_encode((int)$p['district_id'])?>,sc=<?=json_encode((int)$p['city_id'])?>;async function ld(){ed.disabled=true;ed.innerHTML='<option>Loading districts...</option>';const r=await fetch('../customer/get-districts.php?province_id='+ep.value),a=await r.json();ed.innerHTML='<option value="">Select district</option>';a.forEach(x=>{let o=document.createElement('option');o.value=x.id;o.textContent=x.name+' District';if(+x.id===sd)o.selected=true;ed.appendChild(o)});ed.disabled=!a.length;if(ed.value)lc(ed.value)}async function lc(id){ec.disabled=true;ec.innerHTML='<option>Loading towns...</option>';const r=await fetch('../customer/get-cities.php?district_id='+id),a=await r.json();ec.innerHTML='<option value="">Select town / area</option>';a.forEach(x=>{let o=document.createElement('option');o.value=x.id;o.textContent=x.name;if(+x.id===sc)o.selected=true;ec.appendChild(o)});ec.disabled=!a.length}ep.onchange=()=>{sd=0;sc=0;ld()};ed.onchange=()=>{sc=0;lc(ed.value)};ld();
const em=L.map('emap').setView([<?=json_encode($p['latitude']!==null?(float)$p['latitude']:7.8731)?>,<?=json_encode($p['longitude']!==null?(float)$p['longitude']:80.7718)?>],<?=json_encode($p['latitude']!==null?16:7)?>);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(em);let emk=null;const es=document.getElementById('es'),eg=document.getElementById('eg'),est=document.getElementById('est');function setE(lat,lng,addr='',acc=''){elat.value=Number(lat).toFixed(8);elng.value=Number(lng).toFixed(8);eacc.value=acc!==''?Number(acc).toFixed(2):'';if(addr)es.value=addr;em.setView([lat,lng],17);if(!emk){emk=L.marker([lat,lng],{draggable:true}).addTo(em);emk.on('dragend',()=>{let x=emk.getLatLng();setE(x.lat,x.lng,'','')})}else emk.setLatLng([lat,lng]);est.textContent='Service station location selected.';}function pg(u){let m=u.match(/@(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/);if(!m)m=u.match(/!3d(-?\d+(?:\.\d+)?)!4d(-?\d+(?:\.\d+)?)/);if(!m)m=u.match(/[?&](?:q|query|ll|center)=(-?\d+(?:\.\d+)?)[,%2C]+(-?\d+(?:\.\d+)?)/i);return m?[+m[1],+m[2]]:null;}document.getElementById('eguse').onclick=()=>{let c=pg(eg.value);if(c)setE(c[0],c[1],eg.value,'');else est.textContent='Could not read coordinates from this link.'};document.getElementById('egps').onclick=()=>navigator.geolocation.getCurrentPosition(x=>setE(x.coords.latitude,x.coords.longitude,'',x.coords.accuracy),()=>est.textContent='Location permission was denied or unavailable.',{enableHighAccuracy:true});es.oninput=()=>{let q=es.value.trim();if(q.length<3)return;fetch('https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=lk&q='+encodeURIComponent(q)).then(r=>r.json()).then(a=>{if(a[0])setE(a[0].lat,a[0].lon,a[0].display_name,'')})};em.on('click',e=>setE(e.latlng.lat,e.latlng.lng,'',''));<?php if($p['latitude']!==null&&$p['longitude']!==null):?>setE(<?=json_encode((float)$p['latitude'])?>,<?=json_encode((float)$p['longitude'])?>,'',<?=json_encode($p['location_accuracy'])?>);<?php endif;?>
</script><?php require __DIR__.'/../includes/footer.php'; ?>
